apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.revisionName" . }}
data:
  PORT: "{{ include "chart.containerPort" . }}"
  BASE_PATH: {{ .Values.ambassador.prefix }}
  {{- range .Values.env }}
  {{ if .value }}
  {{ .name }}: "{{ .value }}"
  {{end}}
  {{- end }}
