apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.revisionName" . }}
type: Opaque
data:
  {{- range .Values.secret }}
  {{ if .value }}
  {{ .name }}: {{ .value | b64enc }}
  {{end}}
  {{- end }}
